stamped: false
inputs:
  linear:
    x: axis_left_y + button_dpad_up - button_dpad_down
    y: axis_left_x + button_dpad_left - button_dpad_right
  angular:
    z: axis_right_x
scales:
  linear:
    x: 0.30
    y: 0.25
  angular:
    z: 1.57
