polygon_layer:
  resize_to_polygon: true

explore_costmap:
  global_frame: map
  robot_base_frame: base_link
  resolution: 0.02
  update_frequency: 5.0
  publish_frequency: 5.0
  rolling_window: false
  track_unknown_space: true
 
  transform_tolerance: 1
  plugins:
    - {name: static_layer,     type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,   type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
    - {name: polygon_layer,    type: "polygon_layer::PolygonLayer"}