# http://wiki.ros.org/base_local_planner

TrajectoryPlannerROS:
  acc_lim_x: 1.2
  acc_lim_y: 1
  acc_lim_theta: 3.14
  
  max_vel_x: 0.30
  min_vel_x: 0.1
  
  max_vel_y: 0.25
  min_vel_y: 0.1
  
  max_vel_theta: 1.57
  min_vel_theta: -1.57
  min_in_place_vel_theta: 1
  
  escape_vel: -0.30

  holonomic_robot: true
  y_vels: [-0.20, -0.10, 0.10, 0.20]
  
# Goal Tolerance Parametes
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.785
  latch_xy_goal_tolerance: true
  
# Forward Simulation Parameters
  sim_time: 1
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 10
  vy_samples: 10
  vth_samples: 20
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  meter_scoring: true
  path_distance_bias: 0.5
  goal_distance_bias: 0.75
  occdist_scale: 0.03
  heading_lookahead: 0.3
  heading_scoring: false
  heading_scoring_timestep: 0.2
  dwa: true
  publish_cost_grid_pc: true
  global_frame_id: t265_odom_frame
  
# Oscillation prevention parameter
  oscillation_reset_dist: 0.05

# Global plan parameter
  prune_plan: true