# http://wiki.ros.org/dwa_local_planner

DWAPlannerROS:
# Robot Configuration Parameters  
  acc_lim_x: 1.75
  acc_lim_y: 1.25
  acc_lim_th: 4.625

  max_vel_trans: 0.35
  min_vel_trans: 0.1

  max_vel_x: 0.35
  min_vel_x: -0.35
  
  max_vel_y: 0.25
  min_vel_y: -0.25

  max_vel_theta: 1.85
  min_vel_theta: 1

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 1.57
  latch_xy_goal_tolerance: false

# Trajectory Scoring Parameters
  path_distance_bias: 0.5
  goal_distance_bias: 0.75
  occdist_scale: 0.03
  forward_point_distance: 0.3
  stop_time_buffer: 0.1
  scaling_speed: 0.20
  max_scaling_factor: 0.1
  publish_cost_grid: true
  
# Forward Simulation Parameters
  sim_time: 1
  sim_granularity: 0.025
  angular_sim_granularity: 0.05
  vx_samples: 10
  vy_samples: 10
  vth_samples: 20
  controller_frequency: 10.0
  
# Oscillation prevention parameter
  oscillation_reset_dist: 0.05

# Global plan parameter
  prune_plan: true