# http://wiki.ros.org/costmap_2d

footprint: [[0.12, 0.12], [0.12, -0.12], [-0.12, -0.12], [-0.12, 0.12]]
footprint_padding: 0.05
robot_radius: 0.12

# http://wiki.ros.org/costmap_2d/hydro/obstacles
obstacle_layer:
 enabled: true
 
 # Global filtering parameters
 max_obstacle_height: 0.3
 obstacle_range: 2.5
 raytrace_range: 3.5
 
 # ObstacleCostmapPlugin
 track_unknown_space: true
 footprint_clearning_enabled: true
 combination_method: 1
 
 # VoxelCostmapPlugin
 origin_z: 0.0
 z_resolution: 0.2
 z_voxels: 10
 unknown_threshold: 10
 mark_threshold: 0
 publish_voxel_map: false

 # Sensor management parameters
 observation_sources: laser_scan_sensor
 laser_scan_sensor: {topic: rplidar/scan, sensor_frame: laser_frame, observation_persistence: 0.0, expected_update_rate: 0.0, data_type: LaserScan, clearing: true, marking: true, marking: true, max_obstacle_height: 0.3, min_obstacle_height: 0.0, obstacle_range: 2.5, raytrace_range: 3.5, inf_is_valid: false}

# http://wiki.ros.org/costmap_2d/hydro/inflation
inflation_layer:
  enabled: true
  
  cost_scaling_factor:  1.0 
  inflation_radius:     0.10

# http://wiki.ros.org/costmap_2d/hydro/staticmap
static_layer:
  enabled: true
  
  unknown_cost_value: -1
  lethal_cost_threshold: 100
  map_topic: "map"
  first_map_only: false
  subscribe_to_updates: false
  track_unknown_space: true
  use_maximum: false
  trinary_costmap: true

