use_tf_scan_transformation: true
use_tf_pose_start_estimate: false
scan_subscriber_queue_size: 5
map_resolution: 0.02
map_size: 2048
map_start_x: 0.5
map_start_y: 0.5
map_multi_res_levels: 3
update_factor_free: 0.4
update_factor_occupied: 0.9
map_update_distance_thresh: 0.4
map_update_angle_thresh: 0.06
laser_z_min_value: -1.0
laser_z_max_value: 2.0
advertise_map_service: true
# output_timing: false
# pub_drawings: true
# pub_debug_output: true