scan_filter_chain:
- name: angle
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -1.57
    upper_angle: 0.523
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: true
