link_name: base_link
robot_name: akros
linear_scale:
  x: 1
  y: 1
max_positive_linear_velocity:
  x: 0.36
  y: 0.27
max_negative_linear_velocity:
  x: -0.36
  y: -0.27
angular_scale: 1
max_angular_velocity: 1.85
marker_size_scale: 0.30

