# http://wiki.ros.org/base_local_planner

TrajectoryPlannerROS:
  acc_lim_x: 1.4
  acc_lim_y: 1
  acc_lim_theta: 7.4
  
  max_vel_x: 0.35
  min_vel_x: 0.28
  
  max_vel_y: 0.35
  min_vel_y: 0.28
  
  max_vel_theta: 1.85
  min_vel_theta: -1.85
  min_in_place_vel_theta: 1.65
  
  escape_vel: -0.35

  holonomic_robot: true
  y_vels: [-0.35, -0.28, 0.28, 0.35]
  
# Goal Tolerance Parametes
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.75
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1.0
  sim_granularity: 0.04
  angular_sim_granularity: 0.025
  vx_samples: 10
  vy_samples: 10
  vth_samples: 20
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  meter_scoring: true
  path_distance_bias: 0.5
  goal_distance_bias: 0.5
  occdist_scale: 0.03
  heading_lookahead: 0.3
  heading_scoring: false
  heading_scoring_timestep: 0.2
  dwa: true
  publish_cost_grid_pc: true
  global_frame_id: t265_odom_frame
  
# Oscillation prevention parameter
  oscillation_reset_dist: 0.02

# Global plan parameter
  prune_plan: true